config/routes.rb
Rails.application.routes.draw do
resources :posts
root 'posts#index' 

end

app/models/post.rb
class Post < ActiveRecord::Base  
  validates :image, presence: true

  has_attached_file :image, styles: { :medium => "640x" }
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end  

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  def index
    @posts = Post.all
  end

  def show
  end

  def new
    @post = Post.create
  end

  def create
    if @post = Post.create(post_params)
      flash[:success] = "Your post has been created!"
      redirect_to posts_path
    else
      flash[:alert] = "Your new post couldn't be created!  Please check the form."
      render :new
    end
  end

  def edit
  end

  def update
    if @post.update(post_params)
      flash[:success] = "Post updated."
      redirect_to posts_path
    else
      flash[:alert] = "Update failed.  Please check the form."
      render :edit
    end
  end

  def destroy
    @post.destroy
    flash[:success] = "Your post has been deleted."
    redirect_to root_path
  end

  private

  def post_params
    params.require(:post).permit(:image, :caption)
  end

  def set_post
    @post = Post.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html></html>
<head>
  <title>Justagram</title>
  <link href='https://fonts.googleapis.com/css?family=Play' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-default">
    <div class="navbar-container">
      <div class="navbar-header">
        <button class="navbar-toggle collapsed" data-target="#bs-navbar-collapse-1" data-toggle="collapse" type="button">
          <span class="sr-only">Toggle Navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <div class="navbar-brand">
          <%= link_to "Justagram", root_path %>
        </div>
      </div>
      <div class="collapse navbar-collapse" id="bs-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          <li>
            <%= link_to "New Post", new_post_path %>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  <div class="container">
    <%= yield %>
  </div>
  <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
</html>

app/views/posts/edit.html.erb
  <div class="text-center">
  <%= image_tag @post.image.url(:medium) %>
</div>
<div class="form-wrapper">
  <%= simple_form_for @post, html: { class: 'form-horizontal', multipart: true } do |f| %>
    <div class="form-group">
      <%= f.input :image %>
    </div>
    <div class="form-group text-center">
      <%= f.input :caption %>
    </div>
    <div class="form-group text-center">
      <%= f.button :submit, class: 'btn-primary' %>
    </div>
  <% end %>
</div>
<div class="text-center edit-links">
  <%= link_to "Delete Post", post_path(@post), method: :delete, data: { confirm: "Are you sure you want to delete this post?" } %>
  |
  <%= link_to "cancel", posts_path %>
</div>

app/views/posts/form.html.erb
<%= simple_form_for @post, html: { class: 'form-horizontal', multipart: true } do |f| %>
  <%= f.input :image %>
  <%= f.input :caption %>
  <%= f.button :submit %>
<% end %>

app/views/posts/index.html.erb
<div class="posts-wrapper">
  <% @posts.each do |post| %>
    <div class="post">
      <div class="post-head">
        <div class="name">
          JMARCHESENYC
        </div>
      </div>
      <div class="image">
        <%= link_to (image_tag post.image.url(:medium)), post_path(post) %>
      </div>
      <p class="caption">
        <%= post.caption %>
      </p>
    </div>
  <% end %>
</div>

app/views/posts/new.html.erb
<div class="form-wrapper">
  <%= simple_form_for @post, html: { class: 'form-horizontal', multipart: true } do |f| %>
    <div class="form-group">
      <%= f.input :image %>
    </div>
    <div class="form-group text-center">
      <%= f.input :caption %>
    </div>
    <div class="form-group text-center">
      <%= f.button :submit, class: 'btn-success' %>
    </div>
  <% end %>

app/views/posts/show.html.erb
<%= image_tag @post.image.url(:medium) %>
<div class="p">
  <%= @post.caption %>
</div>
<div class="p">
  <%= link_to "Edit Post", edit_post_path(@post) %>
</div>
<div class="text-center edit-links">
  <%= link_to "Cancel", posts_path %>
  |
  <%= link_to "Edit Post", edit_post_path(@post) %>
</div>